#!/bin/bash
echo "BitCracker-BTCFKYEA (criada pelo Sr. Duo)"
echo "ATENÇÃO: BitCracker-BTCFKYEA é um projeto feito para recuperar sua seed phrase bitcoin que você só digitou 11 palavras por algum engano. Se você usar alguma outra carteira que não é sua nisso, sinceramente cara, eu não vou ter NADA a ver se você fazer isso, então já fica esperto"
read -p "Insira o caminho da sua wordlist BIP-39: " caminho
echo "Atenção novamente: Quando sua carteira for encontrada, ela vai ser automaticamente logada na Electrum e a seed phrase dela irá aparecer. Insira as 11 palavras de sua seed phrase para continuar."
read seedphrase11

for i in $(cat $caminho); do
    echo "Tentativa atual: $seedphrase11 $i"
    full_seed="$seedphrase11 $i"
    electrum restore "$full_seed" > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        address=$(electrum listaddresses | head -n 1)
        if [ ! -z "$address" ]; then
            echo "Carteira encontrada! Endereço: $address"
            echo "A seed phrase completa é: $full_seed"
            exit 0
        fi
    fi
done
